# Community configuration for Trilho repository

# Community health files
community:
  # Code of conduct
  code_of_conduct:
    name: "Contributor Covenant"
    url: "https://www.contributor-covenant.org/version/2/0/code_of_conduct/"
    
  # Contributing guidelines
  contributing:
    url: "./CONTRIBUTING.md"
    
  # Issue templates
  issue_template:
    url: "./ISSUE_TEMPLATE/"
    
  # Pull request template
  pull_request_template:
    url: "./PULL_REQUEST_TEMPLATE.md"
    
  # Security policy
  security:
    url: "./SECURITY.md"
    
  # Support
  support:
    url: "./SUPPORT.md"
    
  # Community discussions
  discussions:
    categories:
      - "Announcements"
      - "General"
      - "Help & Support"
      - "Showcase"
      - "Ideas & Feedback"
      - "Development"
      - "Hardware"
      - "Unity"
      - "Web Configurator"

# Community standards
standards:
  # Repository description
  description: "Sistema completo para criação de trilhos digitais interativos que respondem ao movimento físico. Integra hardware ESP32+encoder com Unity para experiências imersivas."
  
  # Repository topics
  topics:
    - "unity"
    - "interactive-media"
    - "physical-computing"
    - "esp32"
    - "encoder"
    - "udp"
    - "interactive-exhibits"
    - "museum-technology"
    - "digital-art"
    - "interactive-installations"
    - "csharp"
    - "javascript"
    - "web-configurator"
    - "real-time"
    - "motion-tracking"
    - "interactive-storytelling"
    - "educational-technology"
    - "immersive-experiences"
    - "physical-digital"
    - "interactive-displays"
    
  # Repository homepage
  homepage: "https://github.com/felipebrito/trilho_unity"
  
  # Repository visibility
  visibility: "public"
  
  # Repository features
  features:
    - "Issues"
    - "Pull requests"
    - "Discussions"
    - "Projects"
    - "Wiki"
    - "Actions"
    - "Packages"
    - "Security"
